version: '3'

services:
  # db:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: slavseat_dev
  #   command: --init-file /data/application/init.sql
  #   volumes:
  #     - ./init.sql:/data/application/init.sql
  #   ports:
  #     - 3306:3306
  redis:
    image: redis:latest
    ports:
      - 6379:6379
